config:
  default:
    url: http://localhost:8080/remote.php/dav/
    #ssl_verify_cert: True
    #ssl_cert: None
    clone_children: True
    detach_from_parent: False
    clone_summary_suffix: " (CLONED)"
    
    # Nextcloud doesn't support TimeZone in tasks : https://github.com/nextcloud/tasks/issues/1233
    # If we apply a filter using a local timezone, the client will properly convert it to UTC
    # For example, if we use 4pm UTC+2, the client will send 2pm UTC, and Nextcloud will think it means 2pm UTC+2
    # Forcing UTC as a workaround
    timezone: "UTC"

    schedules:
      #- category: "3-days"
      #  type: regular
      #  unit: days
      #  value: 3
      - category: "weekly"
        type: regular
        unit: weeks
        value: 1
      #- category: "monthly"
      #  type: regular
      #  unit: months
      #  value: 1
      #- category: "first-monday"
      #  type: monthday
      #  day: "MO"
      #  n: 1
      #- category: "second-tuesday"
      #  type: monthday
      #  day: "TU"
      #  n: 2
      #- category: "last-monday"
      #  type: monthday
      #  day: "MO"
      #  n: -1
  users:
  - name: some_username
    password: some_password
